version: "3.8"
services:
  mc:
    image: itzg/minecraft-server
    container_name: pufferfish
    environment:
      EULA: "true"
      TYPE: PUFFERFISH
      VIEW_DISTANCE: 16
      MEMORY: 4G
      CONSOLE: "false"
      MOTD: "Hey Paddlers!"
      DIFFICULTY: "normal"
      OPS: "Jell0king"
      ICON: "https://img.icons8.com/external-ddara-lineal-color-ddara/64/000000/external-paddle-summer-ddara-lineal-color-ddara.png"
      OVERRIDE_ICON: "TRUE"
      JVM_OPTS: "--add-modules=jdk.incubator.vector"
      SPIGET_RESOURCES: 60837,47136,23307
    ports:
      - 25565:25565
    volumes:
      - ./paddlers-data:/data
    restart: unless-stopped
volumes:
  mc-paper:
