version: "3"
services:
  mc:
    image: itzg/minecraft-server
    container_name: pufferfish
    environment:
      EULA: "true"
      ENABLE_RCON: "true"
      TYPE: PUFFERFISH
      VIEW_DISTANCE: 10
      MEMORY: 5G
      CONSOLE: "false"
      MOTD: "Hey Paddlers!"
      DIFFICULTY: "normal"
      OPS: "Jell0king"
      ICON: "https://img.icons8.com/external-ddara-lineal-color-ddara/64/000000/external-paddle-summer-ddara-lineal-color-ddara.png"
      OVERRIDE_ICON: "TRUE"
    ports:
      - 25565:25565
    volumes:
      - ./paddlers-data:/data
    restart: unless-stopped
volumes:
  mc-paper:
